services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SPRING_BOOT_URL=http://backend:8080/api
    ports:
      - "5173:80"
    environment:
      - VITE_SPRING_BOOT_URL=http://backend:8080/api
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CLICKHOUSE_DEFAULT_HOST=clickhouse
      - CLICKHOUSE_DEFAULT_PORT=8123
      - CLICKHOUSE_DEFAULT_USERNAME=default
      - CLICKHOUSE_DEFAULT_PASSWORD=clickhouse
      - CONFIG_FRONTEND=http://frontend:80, http://localhost:5173
      - JAVA_OPTS=-Dserver.port=8080 -Dserver.servlet.context-path=/api
    volumes:
      - backend_temp:/app/temp
    networks:
      - app-network
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped
    networks:
      - app-network

volumes:
  clickhouse_data:
  backend_temp:

networks:
  app-network:
    driver: bridge
