# Docker-specific configuration

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api
  connection-timeout: 300000  # 5 min timeout
  tomcat:
    max-threads: 200
    max-connections: 8192

# Use environment variables for ClickHouse connection in Docker
clickhouse:
  default:
    host: ${CLICKHOUSE_DEFAULT_HOST:clickhouse}
    port: ${CLICKHOUSE_DEFAULT_PORT:8123}
    protocol: http
    database: ${CLICKHOUSE_DEFAULT_DATABASE:uk}
    username: ${CLICKHOUSE_DEFAULT_USERNAME:default}
    password: ${CLICKHOUSE_DEFAULT_PASSWORD:}

# File upload directory inside Docker container
file:
  upload:
    temp-dir: /app/temp

# Add explicit multipart location for Spring Boot
spring:
  servlet:
    multipart:
      location: /app/temp
      max-file-size: 10GB
      max-request-size: 10GB
      file-size-threshold: 2MB

# Logging to stdout for containerized environment
logging:
  file:
    name: 
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
